# Generated by Django 3.2.4 on 2021-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_numbers'),
        ('wishlists', '0002_auto_20210809_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='products_wishlists', through='wishlists.WishlistItem', to='products.Product'),
        ),
    ]
