# Generated by Django 3.2.4 on 2021-08-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_numbers'),
        ('wishlists', '0004_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_item', to='wishlists.wishlist'),
            preserve_default=False,
        ),
    ]
