# Generated by Django 3.2.4 on 2021-08-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_auto_20210812_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
